// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmC0iOWfxpoi-RGdZwiDRxxs-7zw238eI',
    appId: '1:171006748371:web:b7eadae33131d1170c5626',
    messagingSenderId: '171006748371',
    projectId: 'paypulse-8b158',
    authDomain: 'paypulse-8b158.firebaseapp.com',
    storageBucket: 'paypulse-8b158.firebasestorage.app',
    measurementId: 'G-X66WS7TBEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDziUPo-AY18KZ5vop0XlIudgncdEsgtws',
    appId: '1:171006748371:android:f2b116fb10f343fb0c5626',
    messagingSenderId: '171006748371',
    projectId: 'paypulse-8b158',
    storageBucket: 'paypulse-8b158.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnJhhYdZMSeg6brybZDiCfbtDHxv00Z1s',
    appId: '1:171006748371:ios:3ea4b90f482b48050c5626',
    messagingSenderId: '171006748371',
    projectId: 'paypulse-8b158',
    storageBucket: 'paypulse-8b158.firebasestorage.app',
    iosBundleId: 'com.example.paypulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnJhhYdZMSeg6brybZDiCfbtDHxv00Z1s',
    appId: '1:171006748371:ios:3ea4b90f482b48050c5626',
    messagingSenderId: '171006748371',
    projectId: 'paypulse-8b158',
    storageBucket: 'paypulse-8b158.firebasestorage.app',
    iosBundleId: 'com.example.paypulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmC0iOWfxpoi-RGdZwiDRxxs-7zw238eI',
    appId: '1:171006748371:web:05ec72c8fc3695ef0c5626',
    messagingSenderId: '171006748371',
    projectId: 'paypulse-8b158',
    authDomain: 'paypulse-8b158.firebaseapp.com',
    storageBucket: 'paypulse-8b158.firebasestorage.app',
    measurementId: 'G-H9LP7V52ZD',
  );
}
